export const DEMO_CATEGORIES = [
  {
    id: 'demo-luggage',
    name: 'Luggage',
    image_url: 'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&w=900&q=85',
    sort_order: 1,
  },
  {
    id: 'demo-handbags',
    name: 'Handbags',
    image_url: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=85',
    sort_order: 2,
  },
  {
    id: 'demo-school-bags',
    name: 'School Bags',
    image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=85',
    sort_order: 3,
  },
  {
    id: 'demo-backpacks',
    name: 'Backpacks',
    image_url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=900&q=85',
    sort_order: 4,
  },
];

export const DEMO_PRODUCTS = [
  {
    id: 'demo-trolley-gold',
    name: 'Premium Gold Trolley Bag',
    brand: 'Puccini',
    category: 'Luggage',
    price: 3499,
    sale_price: 3499,
    mrp: 4999,
    original_price: 4999,
    discount_percent: 30,
    description: 'Lightweight premium hard-shell trolley with smooth wheels and secure lock.',
    image_url: 'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&w=900&q=85',
    gallery_images: [
      'https://images.unsplash.com/photo-1581553680321-4fffae59fccd?auto=format&fit=crop&w=900&q=85',
      'https://images.unsplash.com/photo-1599701117045-69f2fb3938b1?auto=format&fit=crop&w=900&q=85',
    ],
    sizes: ['Cabin', 'Medium', 'Large'],
    colors: ['Gold', 'Black', 'Silver'],
    is_active: true,
    featured: true,
    stock: 8,
  },
  {
    id: 'demo-lavie-handbag',
    name: 'Elegant Everyday Handbag',
    brand: 'Lavie',
    category: 'Handbags',
    price: 1899,
    sale_price: 1899,
    mrp: 2999,
    original_price: 2999,
    discount_percent: 37,
    description: 'A premium handbag for daily elegance with spacious compartments.',
    image_url: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=85',
    gallery_images: [
      'https://images.unsplash.com/photo-1605733513549-de9b150bd70f?auto=format&fit=crop&w=900&q=85',
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85',
    ],
    sizes: ['Standard'],
    colors: ['Beige', 'Tan', 'Black'],
    is_active: true,
    featured: true,
    stock: 5,
  },
  {
    id: 'demo-school-mint',
    name: 'Ready For More School Bag',
    brand: 'Wildcraft',
    category: 'School Bags',
    price: 1299,
    sale_price: 1299,
    mrp: 1999,
    original_price: 1999,
    discount_percent: 35,
    description: 'Durable school bag with spacious storage and water-resistant finish.',
    image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=85',
    gallery_images: [
      'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=900&q=85',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85',
    ],
    sizes: ['Junior', 'Senior'],
    colors: ['Mint', 'Blue', 'Black'],
    is_active: true,
    featured: true,
    stock: 12,
  },
  {
    id: 'demo-backpack-black',
    name: 'Urban Laptop Backpack',
    brand: 'Arctic Fox',
    category: 'Backpacks',
    price: 1599,
    sale_price: 1599,
    mrp: 2499,
    original_price: 2499,
    discount_percent: 36,
    description: 'Work-ready backpack with laptop section, organizer pockets, and premium finish.',
    image_url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=900&q=85',
    gallery_images: [
      'https://images.unsplash.com/photo-1491637639811-60e2756cc1c7?auto=format&fit=crop&w=900&q=85',
    ],
    sizes: ['Standard'],
    colors: ['Black', 'Grey'],
    is_active: true,
    featured: true,
    stock: 9,
  },
];

export const DEMO_OFFERS = [
  {
    id: 'demo-offer-1',
    title: 'New Arrivals Deal',
    code: 'SETHI10',
    description: 'Get special launch pricing on selected luggage and handbags.',
    discount_percent: 10,
    banner_url: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?auto=format&fit=crop&w=1000&q=85',
    is_active: true,
  },
];

export const DEMO_REVIEWS = [
  {
    id: 'demo-review-1',
    customer_name: 'Amanpreet Kaur',
    rating: 5,
    comment: 'Excellent collection and very helpful staff. The trolley quality is premium.',
    review_text: 'Excellent collection and very helpful staff. The trolley quality is premium.',
    is_approved: true,
    is_featured: true,
  },
  {
    id: 'demo-review-2',
    customer_name: 'Rohit Sharma',
    rating: 5,
    comment: 'Best prices in Jalandhar. Bought school bags and luggage from here.',
    review_text: 'Best prices in Jalandhar. Bought school bags and luggage from here.',
    is_approved: true,
    is_featured: true,
  },
];
